[tool.poetry]
name = "cvxcli"
version = "0.0.0"
description = "Simple command line app demo"
authors = ["Thomas Schmelzer"]
readme = "README.md"
repository = "https://github.com/cvxgrp/cvxcli"
packages = [{include = "cvx"}]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
fire = "*"
cvxbson = "*"
requests = "*"

[tool.poetry.group.test.dependencies]
pytest = "7.2.0"
pytest-cov = "4.0.0"
mock = "*"

[tool.poetry.scripts]
weather = "cvx.cli.weather:main"
smallest-eigenvalue = "cvx.cli.smallest_eigenvalue:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
select = ["E", "F", "I"]
line-length = 120
target-version = "py310"
exclude = [
    "*__init__.py"
]
